### ISSUE TITLE
Клиент отправляет неверное время операций на сервер

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#100]
При создании операции поле changeTime хранит в себе только дату, но не время операции. Т.е. на сервер всегда уходит полночь. Из-за этого сбои в расчетах. Нужно либо отказать от ручного выбора времени при создании операции (вовсе убрать это поле из UI), либо заменить компонент для выбора времени. Например, на такой https://eonasdan.github.io/bootstrap-datetimepicker/. 

В случае отказа нужно при сохранении операции руками проставлять в это поле текущее клиентское время.

@hodkoff2 отказаться - это быстрый и вполне себе рабочий вариант. Конечно легко представить ситуацию, когда платеж нужно завести "на вчера", но на первое время и так должно пойти. Как ты считаешь?

Или, если @Argelein чувствует в себе силы разобраться с использованием предложенного мной контрола, то вариант замены представляется более привлекательным.

**Comment by sedovalx** [comment]
Юбилейная задача, кстати :birthday: :cocktail: :collision: :tada:

**Comment by sedovalx** [comment]
Пока сам попробую, тут все неочевидно.

**Comment by sedovalx** [comment]
@Argelein теперь для выбора времени используй контрол как в мастере операций. Его описание есть в шапке задачи. Можно использовать его в режиме выбора только даты или только времени.

**Comment by hodkovdd** [comment]
@sedovalx 
Все еще нет операций в истории аренды. Стенд обновил сегодня.
![38](https://cloud.githubusercontent.com/assets/4660424/8825357/2b52bcea-3087-11e5-9244-34e12f438a5e.png)

... Нужно либо отказать от ручного выбора времени при создании операции (вовсе убрать это поле из UI) ... Убираем.

**Comment by kirzas** [comment]
https://github.com/sedovalx/taxi/issues/94#issuecomment-123834421
у меня работает

**Comment by hodkovdd** [comment]
Ок, проверил на стенде, закрываю.
