### ISSUE TITLE
Явка с клиента на сервер

### ISSUE THREAD

**Issue by kirzas** [sedovalx/taxi#104]
Мое предположение такое:
Если водитель пришел и оплатил что-то, при этом ему проставили явку true, например в 10 часов утра. А потом в тот же день в 11 часов утра на него пришел штраф и ему автоматически заполнилась явка false. В этом сценарии вечером увидим, что явки не было.

Я не знаю, как это сейчас происходит, если все ок, то просто надо закрыть задачу.

Если эта проблема есть, то предлагаю серверной части реагировать только на явку true, в противном случае игнорировать это свойство.

**Comment by sedovalx** [comment]
Я ничего не понял. Сейчас последующие платежи вроде бы не влияют на галку явки в КС. Достаточно одной явки за сегодня, чтобы в КС отобразилась галка. Закрываю. Если я что-то не так понял, переоткрой. 

К багам бизнес-логики подключай Диму, кстати. Может это и не баг вовсе, а фича :)
