### ISSUE TITLE
Свойство carDisplayName модели rent не совпадает с свойством displayName модели car

### ISSUE THREAD

**Issue by kirzas** [sedovalx/taxi#107]
Свойство carDisplayName модели rent не совпадает с свойством displayName модели car. Там с сервера приходит string в обоих случаях, но формат разный, с нулями и без.

**Comment by sedovalx** [comment]
Где это можно увидеть в UI?

**Comment by sedovalx** [comment]
Проблемы две:
- Наименование машины отображается по разному в первом столбце кассовой формы и в редакторе аренды
- Тариф по машине в редакторе и списке машин отображается без нулей после точки (.00), а в кассовой форме и редакторе аренды с нулями.

**Comment by sedovalx** [comment]
Первое починил, а второе - это вероятно особенность преобразования строки в число в Ember. С сервера тариф приходит в виде "1234.00", а после преобразования в число получается просто 1234. Причем, если приходит "1234.56", то получаем 1234.56. Можно наверное в редакторе и списке машин форматировать число при отображении, но это представляется лишним гемороем.
