### ISSUE TITLE
Реализовать UserController с полным набором методов и роутингом

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#2]
В приложении должна быть сущность User. У него должны быть свойства:
1. Имя
2. Фамилия
3. Отчество
4. Роль notnull
5. Логин notnull
6. Пароль notnull

Как и у всех остальных сущностей у пользователя должны также быть свойства:
7. Дата создания notnull
8. Дата последнего редактирования
9. Создатель
10. Последний отредактировавший
Возможно все классы сущностей должны реализовывать общий интерфейс/трейт или иметь общего предка. Правда в Slick с наследованием все не так просто.

Для данной сущности нужно реализовать CRUD-контроллер. Это должен быть эталонный контроллер, примеру которого потом будут сделаны контроллеры остальных сущностей. 
- Он должен использовать хранилище, не зная о его реализации - Slick это или что-то другое (см. #9).
- В нем (а может и в хранилище) должно быть предусмотрено единая точка для простановки создателя/изменившего и соответствующих дат при изменении данных.
- Он должен удовлетворять требованиям [Ember Data REST](http://emberjs.com/guides/models/the-rest-adapter/) adapter, который ожидает следующий серверный Api для сущности данных:

> Find   GET /api/users/123
> Find All   GET /api/users
> Update PUT /api/users/123
> Create POST    /api/users
> Delete DELETE  /api/users/123
- Нужно учесть, что Ember всегда ожидает что-то в respons'е. Даже при удалении он ожидает пустой json-объект. Кое-что об этом описано по ссылке на rest-адаптер выше, остальное должно быть в секции [REST Srializer](http://www.toptal.com/emberjs/a-thorough-guide-to-ember-data).
- Для метода GET /api/users нужно предусмотреть наличие query params в запросе (см. #11). В частности - параметры фильтрации по любому из полей сущности. В запросе они будут приходить в следующем виде: `/api/users?filter.lastname=Иванов&filter.role=Accountant&filter.creationdate=2011-12-30T22:00:00`
- Нужно реализовать соответствующие методы UserController и прописать по ним роутинг в конфигурации.
- Должна быть предусмотрена точка для выполнения валидации полученных с клиента данных. Не прошли валидацию - бросаем ошибку с пояснением. Это помимо авторизации.

Про аутентификацию и авторизацию пока не думаем, она должа достаточно просто добавляться (см. #4)

Соприкасается с #1 и #4

**Comment by sedovalx** [comment]
@v1pka, непонятые мной моменты:
1. Зачем в GenericCRUD.update передавать id, если в entity он уже есть?
2. Есть какие-то мысли по реализации фильтра в методе GenericCRUD.read?

**Comment by v1pka** [comment]
@sedovalx 
1. Сакральная копипаста. Да, не нужно.
2. Что ты имеешь ввиду? Уточни, плиз.

**Comment by sedovalx** [comment]
В приложении будут списки. Скажем, список пользователей. У списка будет фильтр. Например, можно будет фильтровать по ФИО, логину, роли. Выбранные параметры фильтрации будут передавать на сервер в виде

   GET /api/users?filter.role=Administrator&filter.lastName=Smith

Нужно будет возвращать данные согласно такому фильтру. Вероятно у метода GenericCRUD.read должен быть параметр, определяющий фильтрацию возвращаемых данных. В фильтре в общем случае могут присутствовать все поля сущности, а могут и отсутствовать. Я пока не придумал, как это удобно сделать. Есть пара "плохих" идей:
- В GenericCRUD.read передавать JSON, а дальше его поля сравнивать по совпадению имени с полями в entity-классе.
- Для каждого entity класса делать двойник, у которого будут те же поля, но все с типом Option[тип]

Вот может у тебя есть более интересные идеи?

**Comment by sedovalx** [comment]
К слову о создании сессии к БД - есть ж DBAction в play-slick

**Comment by sedovalx** [comment]
При вставке пользователя Postgre выкидывает смешное исключение: 

> [debug] s.s.j.J.statement - Preparing insert statement: insert into "user" ("login","password","last_name","first_name","middle_name","role","creation_date","edit_date","creator_id","editor_id")  values (?,?,?,?,?,?,?,?,?,?), returning: id 
> [error] play - Cannot invoke the action, eventually got an error: org.postgresql.util.PSQLException: ╬╪╚┴╩└: яютЄюЁ ■∙ххё  чэрўхэшх ъы■ўр эрЁє°рхЄ юуЁрэшўхэшх єэшъры№эюёЄш "user_pkey"  
>   ╧юфЁюсэюёЄш: ╩ы■ў "(id)=(2)" єцх ёє∙хёЄтєхЄ.    

Расшифровать пока не успел :)

**Comment by sedovalx** [comment]
Расшифровал - дело в том, что я до этого руками вбил нескольких пользователей, причем указал для них id самостоятельно. Внутренний счетчик Postgrej об этом ничего не знал, в результате получались повторяющиеся id. После нескольких попыток все сработало. Однако новая ошибка:

> Error: Assertion Failed: An adapter cannot assign a new id to a record that already has an id. <client@model:user::ember473:0> had id: 0 and you tried to update it with 7. This likely happened because your server returned data in response to a find or update that had a different id than the one you sent.

**Comment by sedovalx** [comment]
Контроллер есть. Неидеальный, но все правки - отдельными задачами.
