### ISSUE TITLE
Описать таблицы всех доменных сущностей

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#21]
По примеру таблицы пользователей в server/app/models/tables/Users.scala нужно описать все таблицы нашей доменной модели. Так же в помощь [документация по Slick](http://slick.typesafe.com/doc/2.1.0/schemas.html) и [вот этот блог](http://blog.lunatech.com/tags/slick). Схема модели данных будет актуализирована в рамках #20

**Comment by sedovalx** [comment]
Тут вроде бы все. Какие-то доделки вероятно будут, но это отдельными задачами.

**Comment by kirzas** [comment]
@sedovalx  @hodkoff2 
Это значит, что я в клиентской части могу без Fixtures ко всем объектам в таблице обращаться? или это что-то другое?

**Comment by kirzas** [comment]
@sedovalx  и надо ли мне в клиентской части user на account менять?

**Comment by sedovalx** [comment]
@Argelein нет, не значит. Пока Дима не сделает контроллер и сериализацию для каждой из новых сущностей, на клиенте нужны будут FIXTURES. На клиенте менять необязательно, но для единообразия можно. Как хочешь.
