### ISSUE TITLE
Сделать список/редактор автомобилей

### ISSUE THREAD

**Issue by kirzas** [sedovalx/taxi#37]
Делать нужно по примеру списка и редактора пользователей и водителей.
1. Определиться с набором атрибутов у типа Автомобиль: наименование, тип, обязательность (nullable или not null)
2. Описать атрибуты Автомобиля в docs/domainModel2.vsx
3. Описать тип модели Автомобиля в каталоге client/app/models
4. Пока нет реализации на стороне сервера добавить FIXTURE-адаптер для типа Автомобиль в каталоге client/app/adapters
5. Описать маршруты к списку, визарду и редактору Автомобиля в файле client\app\router.js
6. Описать шаблон (app\templates\drivers\index.hbs) и контроллер (app\controllers\drivers\index.js) списка Автомобилей
7. Описать шаблон (app\templates\drivers\new.hbs) и контроллер (app\controllers\drivers\new.js) визарда Автомобилей
8. Описать шаблон (app\templates\driver\edit.hbs) и контроллер (app\controller\driver\edit.js) Автомобиля 
9. Для кнопок в списке Автомобилей прописать обработчики с открытием визарда, редактора, а так же удалением Автомобиля .

**Comment by sedovalx** [comment]
@Argelein не забывай использовать protected маршруты. Смотри, как сделано для водителя. Это нужно для аутентификации.

**Comment by kirzas** [comment]
@sedovalx это ты просто, чтобы я не забыл, или где-то ошибку нашел?
Я вроде везде, где были для водителей protected, для машин также сделал.
Если увидел ошибку, не иправляй, пожалуйста, напиши где, чтобы я сам исправил.
Или в крайнем случае при коммите меня укажи ,чтобы я мог посмотреть.

**Comment by sedovalx** [comment]
@Argelein оу, пардон, все ок!

**Comment by sedovalx** [comment]
Зависит от #39

**Comment by sedovalx** [comment]
@Argelein что тут еще осталось сделать?

**Comment by kirzas** [comment]
@sedovalx 
надо с серверной части прикрутить коннектор и после этого удалить Fixtures
