### ISSUE TITLE
Рефакторинг разметки редакторов и мастеров

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#42]
В редакторах и мастерах очень много похожей разметки по созданию поля ввода с меткой. Нужно это вынести в [Ember-компоненты](http://guides.emberjs.com/v1.11.0/components/).

**Comment by Argelein** [comment]
@sedovalx 
мне нужно, чтобы были параметры, типа readonly, которые есть в input. Они оттуда наследуются? У меня не работает.
Это нужно, чтобы некоторые свойства нельзя было менять, типа логина у пользователя, например.
