### ISSUE TITLE
Переписать текущие редактора/мастера с использованием property-row

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#44]
В рамках #42 были созданы хелперы `property-row` и `save-cancel`. Читай о них [тут](https://github.com/sedovalx/taxi/wiki/%D0%A0%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0.How-to.%D0%A0%D0%B0%D0%B7%D0%BC%D0%B5%D1%82%D0%BA%D0%B0). Я переписал мастер пользователя (templates/cars/new.hbs) с их использованием. Тебе нужно разобраться в них, если что-то неясно, задать вопросы и переписать с их использованием остальные редактора/мастеры.

**Comment by kirzas** [comment]
@sedovalx
мне нужно, чтобы были параметры, типа readonly, которые есть в input. Они оттуда наследуются? У меня не работает.
Это нужно, чтобы некоторые свойства нельзя было менять, типа логина у пользователя, например.

**Comment by kirzas** [comment]
@sedovalx 
вот так работает:
      {{#property-row title="Логин" errors=errors.login}}
        {{input value=login readonly="true"}}
      {{/property-row}}

Это ок?

**Comment by sedovalx** [comment]
@Argelein да, именно так

**Comment by kirzas** [comment]
@sedovalx 
для тех сущностей, которые на FIXTURES, естесственно, не работает проверка и можно создать как угодно, без правил

**Comment by sedovalx** [comment]
@Argelein это понятно. Но мы же не планируем так и оставлять с fixtures.

**Comment by kirzas** [comment]
@sedovalx 
А для водителей тоже не работает, пишет просто bad request, ноошибки не возвращает, как для пользователей.

**Comment by sedovalx** [comment]
@Argelein что не работает? + смотри ошибку в консоли у сервера

**Comment by kirzas** [comment]
@sedovalx 
не работает вывод ошибки заполнения поля рядом с полем, как для пользователей.
Просто ничего не происходит, а в F12 ошибка Bad request:

POST http://localhost:9000/api/drivers 400 (Bad Request)jQuery.ajaxTransport.send @ jquery.js:9659jQuery.extend.ajax @ jquery.js:9210ember$data$lib$system$adapter$$Adapter.extend.ajax @ rest_adapter.js:899initializePromise @ ember.debug.js:50488Promise @ ember.debug.js:52116ember$data$lib$system$adapter$$Adapter.extend.ajax @ rest_adapter.js:883ember$data$lib$system$adapter$$Adapter.extend.createRecord @ rest_adapter.js:530ember$data$lib$system$store$$_commit @ store.js:2048(anonymous function) @ store.js:1223forEach @ ember.debug.js:12224Ember.Object.extend.flushPendingSave @ store.js:1205Queue.invoke @ ember.debug.js:854Queue.flush @ ember.debug.js:919DeferredActionQueues.flush @ ember.debug.js:724Backburner.end @ ember.debug.js:149Backburner.run @ ember.debug.js:204run @ ember.debug.js:16638handleRegisteredAction @ ember.debug.js:19064(anonymous function) @ ember.debug.js:39488jQuery.event.dispatch @ jquery.js:4665jQuery.event.add.elemData.handle @ jquery.js:4333

Error: Bad Request
    at ember$data$lib$system$adapter$$Adapter.extend.ajaxError (rest_adapter.js:820)
    at superFunction [as _super](ember.debug.js:14376)
    at ajaxError (application.js:8)
    at apply (ember.debug.js:18630)
    at superWrapper [as ajaxError](ember.debug.js:18195)
    at ember$data$lib$system$adapter$$Adapter.extend.ajax.Ember.RSVP.Promise.hash.error (rest_adapter.js:896)
    at jQuery.Callbacks.fire (jquery.js:3143)
    at Object.jQuery.Callbacks.self.fireWith [as rejectWith](jquery.js:3255)
    at done (jquery.js:9311)
    at XMLHttpRequest.jQuery.ajaxTransport.send.callback (jquery.js:9713)

**Comment by sedovalx** [comment]
@Argelein на сервере в консоли смотри. Там, где ты запускаешь сервер.

**Comment by kirzas** [comment]
@sedovalx  Собственно причина понятна, я не заполнил обязательные поля. Если я их заполню, то все создается.
Но для пользователя выводится ошибка заполнения поля рядом с полем, а для водителя это не работает.

**Comment by kirzas** [comment]
@sedovalx 
хрень какая-то:
теперь создает водителей в любом случае, даже, если поля не заполнены

**Comment by kirzas** [comment]
[debug] s.s.j.J.statement - Preparing statement: select x2."id", x2."login", x2."password_hash", x2."last_name", x2."first_na
me", x2."middle_name", x2."role", x2."comment", x2."creation_date", x2."edit_date", x2."creator_id", x2."editor_id" from "acc
ount" x2 where x2."login" = 'admin'

**Comment by kirzas** [comment]
@sedovalx 
я запушил, в принципе создание и правка работает, но некорректно работает проверка правильности заполнения полей

**Comment by sedovalx** [comment]
@Argelein была ошибка в серверной валидации. Поправил.

**Comment by sedovalx** [comment]
@Argelein как переделаешь существующие, закрывай эту задачу. Кстати, закрывать ее можно с помощью [специально отформатированного комментария](https://help.github.com/articles/closing-issues-via-commit-messages/) к коммиту. Например, `Fixed #44: какой-то комментарий` закроет задачу №44.
