### ISSUE TITLE
Изменение модели платежа

### ISSUE THREAD

**Issue by kirzas** [sedovalx/taxi#48]
@hodkoff2 
В модели объекта payment заменил имя поля target на rent.

**Comment by hodkovdd** [comment]
@Argelein 
я нашел и понял что изменилось.

**Comment by sedovalx** [comment]
@Argelein @hodkoff2 задача все еще актуальна? Если нет, закрывайте.

**Comment by sedovalx** [comment]
Тогда закрываю
