### ISSUE TITLE
Сделать список/редактор платежей

### ISSUE THREAD

**Issue by kirzas** [sedovalx/taxi#49]
Аналогично прочим объектам

**Comment by kirzas** [comment]
Надо добавить фильтрацию аренд, при создании новых платежей, чтобы исключить закрытые аренды.
Добавлю позже.

**Comment by kirzas** [comment]
И сделать загрузку автомобилей и водителей, по которым есть платежи.
В контроллере или в модели аренды.

**Comment by sedovalx** [comment]
@Argelein обрати внимание на использование 
- [bootstrap-datepicker](http://sul.im/ember-cli-bootstrap-datepicker/) для редактирования даты платежа
- [momentjs](http://momentjs.com/docs/) для отображения даты в списке

**Comment by kirzas** [comment]
@sedovalx 
ошибка при переходе в payments/new:
Uncaught Error: Assertion Failed: A helper named 'bootstrap-datepicker' could not be found

**Comment by sedovalx** [comment]
@Argelein выполни `npm install & bower install`

**Comment by kirzas** [comment]
@sedovalx 
ага уже увидел, спасибо
