### ISSUE TITLE
Ввести понятие счета

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#58]
Счет состоит из суммы на счету и уникального наименования/назначения + стандартные comment, creator_id и пр.

Предполагается наличие двух счетов: 
- Кассовый счет. Будет пополняться платежами по арендам. Списания с него будут происходить в виде переводов средств на расчетный счет.
- Расчетный счет. Пополняется только переводами из кассы. Все расходы `expences` будут привязаны к нему.

Новые платежи по аренде меняют состояние кассового счета в большую сторону - он увеличивается. Перевод на расчетный счет меняет состояние в меньшую сторону - он уменьшается. Нельзя перевести больше, чем есть на кассовом счету.

**Вопросы**: 
- Что делать с состоянием кассового счета, если администратор редактирует платеж? Наверное, автоматически изменять значение кассового счета.
- Что делать, если был совершен платеж А1, затем был перевод из кассового счета на расчетный, потом совершен платеж А2, а затем администратор отредактировал платеж А1? Наверное, нужно разрешать редактировать только те платежи, которые еще не попали ни в какой перевод.

**Comment by sedovalx** [comment]
@hodkoff2 @Argelein что думаете?

**Comment by kirzas** [comment]
@sedovalx @hodkoff2 
Нужно еще понятие трансфера, т.е. списания с кассового в расчетный счет.
Я предлагаю такую схему:
У счета будут следующие свойства:
1. transactions - Массив идентификаторов платежей/затрат.
2. balance - Сумма денег.
3. lastTransfer - id последнего трансфера (Пока я не придумал, нужно ли это хранить, но мне кажется, что не помешает)

Обзову два счета cash и operating. И предполагаю, что они являются объектами одного класса.

Transfer же в свою очередь тоже должен содержать по сути те же поля, их можно назвать по другому:
1. payments - Массив идентификаторов платежей.
2. amount - Сумма денег.
3. previousTransfer - id предидущего трансфера.

transactions счета cash наполняется платежами, при их создании. Т.е. создали платеж, он автоматически добавился в cash.transactions.
cash.balance считается автоматически из cash.transactions. Это можно расчитывать в SQL или в серверной части.
При создании трансфера:
1. cash.transactions обнуляется. cash.balance обнудяется тоже, т.к. расчитывается из cash.transactions.
2. в новый трансфер в свойство previousTransfer записывается значение предидущего трансфера из cash.lastTransfer.
3. cash.lastTransfer перезаписывается идентификатором нового трансфера.

И да, платеж нельзя редактировать после того, как он попал в transfer.

**Comment by sedovalx** [comment]
@Argelein воу-воу! Полегче :) Смотри вот это #60 . Я почти уверен, что нам не нужно хранить состояние счета нигде, иначе получим кучу проблем с синхронизацией изменений.

**Comment by kirzas** [comment]
этот пункт тогда отменяется?

**Comment by sedovalx** [comment]
@Argelein да.
