### ISSUE TITLE
Именованные запросы в базу

### ISSUE THREAD

**Issue by kirzas** [sedovalx/taxi#62]
@sedovalx @hodkoff2 
Предлагаю здесь описать именованные запросы к серверу и я могу их начать писать.
Буду править этот коммент.

**Comment by kirzas** [comment]
@hodkoff2 
Вопрос по виду главного списка, который нарисован в Funktsii.vsd (автомобиль, водитель, балансы и проч.)
В этом списке должны быть все машины? если у машины нет аренды она там должна быть?

**Comment by hodkovdd** [comment]
@Argelein
Да, если это возможно.

**Comment by kirzas** [comment]
@hodkoff2 
Наваял кассовую форму, посмотри скриншот.
Я ее еще не пушил, т.к. там есть ошибки и баланс не считается, но посмотри сейчас.
![capture](https://cloud.githubusercontent.com/assets/10670155/7566891/2c09164c-f802-11e4-970d-e96d446eebd5.JPG)

**Comment by sedovalx** [comment]
На каждый запрос - отдельную задачу.
