### ISSUE TITLE
Перейти на Slick 3.0

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#67]
Тем временем вышла [третья](http://slick.typesafe.com/doc/3.0.0/) версия Slick. Что бросается в глаза, так это асинхронность запросов в БД (можно заценить в [слайд-шоу](http://slick.typesafe.com/talks/scaladays2015sf/Reactive_Slick_for_Database_Programming.pdf)). Так же доступен [гайд](http://slick.typesafe.com/doc/3.0.0/upgrade.html) по переходу от версии 2.1

**Comment by hodkovdd** [comment]
@sedovalx 
Сколько займет переход на новые Slick и Play Framework?

**Comment by sedovalx** [comment]
@hodkoff2 хз, это в низком приоритете - когда время появится.

**Comment by hodkovdd** [comment]
@sedovalx 
Ok

**Comment by sedovalx** [comment]
Пришлось начать миграцию. Причина следующая - у нас появилась сложная функциональность подсчета балансов в виде sql-запросов. PostgreSql с ними отлично справляется, а вот h2, которая использовалась для эмуляции реальной БД во время прогона тестов, уже не тянет. Для тестов нужно так же использовать PostgreSql, что не так просто, как казалось. В итоге оказалось, судя по документации, что с Slick 3.0.0 это проще сделать. А эта зараза без Play 2.4 не работает.

**Comment by hodkovdd** [comment]
@sedovalx 
И чем нам это грозит по времени?

**Comment by sedovalx** [comment]
@hodkoff2 надеюсь, за пару дней сделаю. Если так и выйдет, то все еще есть шанс успеть к выходным доделать кассовую форму. Но это не 100%. Постараюсь.
