### ISSUE TITLE
Генератор тестовых данных

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#69]
Настал момент, когда нужно наполнить БД чем-то и посмотреть, как будут строиться списки. Для этого нужен генератор тестовых данных, который будет создавать некоторый достаточно обширный набор машин, водителей, аренд и прочего. Предполагается дергать генератор через вызов http-метода.

**Comment by sedovalx** [comment]
https://github.com/sedovalx/taxi/wiki/%D0%A0%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0.How-to.%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D1%85-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85

**Comment by hodkovdd** [comment]
@sedovalx 
Ты используешь генератор на локальном инстансе или в амазоне тоже можно посмотреть?
