### ISSUE TITLE
Отображать список операций по выбранной аренде

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#76]
Сейчас сервер поддерживает получение всех операций по указанной аренде, получение всех операций заданного типа и получение операций заданного типа по указанной аренде. Пример:
`GET /api/operations?rent=345&accountType=Repair`
По сути это такая же функциональность фильтрации, как сделано для списка пользователей. 

На клиенте в списке аренд нужно сделать реализации для уже присутствующих кнопок перехода к штрафам, ремонтам и платежам. По нажатию на них должен открываться список операций, отфильтрованный по выбранному типу операции и идентификатору самой аренды. В идеале нужно сделать в этом списке UI-фильтр по типу операции. В результате при переходе к нему, скажем, по кнопке "Перейти к платежам" он должен отображаться с уже предустановленным типом операции.

Для списка должны быть предусмотрены команды создания, удаления и редактирования. При создании аренда должна проставляться автоматически. При редактировании поля аренды и типа операции должны быть доступны только на чтение.

Маршрут для такого списка может быть следующим `/rents/361/operations?accountType=Rent`

По нажатию на кнопку должен вызываться 

```
this.transitionToRoute("rents", this.get("model").id, {
    queryParams: { accountType:  'some type' }
});
```

Первоначальное описание:
Ориентироваться сложно. Если хочешь посмотреть, какие у аренды платежи, непонятно как это сделать. Да, будут фильтры, они помогут, но это неудобно. Лучше перенести все списки изменения баланса аренды на отдельные вкладки редактора аренды. В этом случае, открыв этот редактор, можно будет сразу увидеть все платежи, штрафы и ремонты **по ней**.

**Comment by hodkovdd** [comment]
@sedovalx 
Как это было нафантазировано на дизайн-схеме:
![-](https://cloud.githubusercontent.com/assets/4660424/8103998/e679fc9e-1035-11e5-9e06-3f8b0e57b2ef.png)
Зеленая стрелка - клик.
Прокомментируй, пожалуйста.

**Comment by sedovalx** [comment]
@hodkoff2 @Argelein  ну да, примерно так теперь и будет, т.к. больше не будет отдельных списков с штрафами, ремонтами и платежами. Будет один с операциями, у которых есть тип. Выбираешь строку с арендой в кассовой форме **нажимаешь кнопку** и попадаешь в список операций по этой аренде, отсорированный по дате операции. Почему кнопку? Ну так сделать проще.

**Comment by hodkovdd** [comment]
@sedovalx @Argelein 
В продолжение этой темы - там есть еще кусок переходов на отдельные списания с детализацией:
![detalization spisation](https://cloud.githubusercontent.com/assets/4660424/8153806/c5b587e0-133b-11e5-840d-0b0a2ceb9c24.png)
Переход может быть также по кнопке, а не клику, это не принципиально.
Необходимость в том, что водители всегда оспаривают сумму баланса когда им ее назовешь. Ситуация: стоит очередь водителей с деньгами, все подходят
- называют фамилию
- кассир находит их в кассовой форме, называет сумму к оплате, например "с вас, Петров, 5000"
- водитель возмущается "как 5000?"
- кассир показывает ему сумму на экране
- водитель - "я ж платил, с хера ли?"
- кассир открывает сводную таблицу платежей\зачислений по водителю (решается вопрос кто когда платил, если водитель утверждает что платил, а сведений об этом нет, вопрос решается организационными мерами)
- водитель - "а откуда вот этот штраф\ремонт?"
- кассир открывает детализацию по конкретному списанию прямо из сводной таблицы  - в форме указаны дата, имя занесшего, сумма,расшифровка и фото как доказательство факта нарушения\повреждения. Если водитель оспаривает - снова оргмеры.

В условиях очереди диалог должен быть коротким, кассир должен быстро разбираться с такими вопросами, отсюда необходимость удобной навигации.

Саша, дальше текст скорее всего нужно перенести в другой issue, пишу здесь потому что информация связана и пусть она появиться здесь, будет понимание откуда ноги растут. Заказчика предупредил, что этот функционал в первом релизе не будет реализован:

Чтобы снизить нагрузку от конфликтов и оргмер, заказчик просил добавить функцию формирования и хранения расписок, в том, что водитель признает наличие нарушения\повреждения и обязуется его выплатить. Чтобы через неделю, когда он будет возмущаться, что ничего не было, а запись в базе развод честного человека на деньги, одной кнопкой из формы детализации списания отобразить подписанную им ранее расписку.
Расписка это шаблон текста в который подставляется дата,ФИО,сумма конкретного списания.

**Comment by sedovalx** [comment]
@Argelein вот тебе задача. Обновил описание, если что непонятно, спрашивай.

**Comment by hodkovdd** [comment]
@sedovalx @Argelein 
готовность? Серверная, клиентская стороны?

**Comment by sedovalx** [comment]
На серверной стороне все для этого есть. Остальное за @Argelein

**Comment by hodkovdd** [comment]
Когда сделаешь остальное?  @Argelein

**Comment by kirzas** [comment]
@sedovalx 
сейчас для operations в route модель определяется так:
  model: function(params, transition) {
    $.getJSON("/api/reports/q-operation-list", { rent: transition.params.rent.rent_id }).then(function(data){
      console.log(data);
    });

Я не понимаю, как туда accountType передать. Можно это заменить на this.store.find?

**Comment by kirzas** [comment]
так совсем не работает:
GET http://localhost:9000/api/reports/q-operation-list?rent=1&accountType=Fine 404 (Not Found)

**Comment by kirzas** [comment]
@sedovalx 
так работает:
return this.store.find("operation", { rent: transition.params.rent.rent_id, accountType: 'Fine' });
это парвильно? это у тебя тут просто от тестирования что-то осталось?

**Comment by kirzas** [comment]
@hodkoff2 
работает
Можно еще сделать просмотр всех платежей, без выбора типа. Нужно так?
Дим, и подписи на кнопках посмотри. Может как-то получше можно написать и поменять местами.

**Comment by sedovalx** [comment]
В целом нормально. Тут идея возникла отображать все операции вместе со статусами аренды в хронологическом порядке - самый свежий инцидент. Взгляни.

**Comment by sedovalx** [comment]
Более неактуально. История операций будет отображаться в редакторе аренды. См. #85
