### ISSUE TITLE
Перейти на понятия счета, списания и зачисления

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#78]
Задача заведена на основании обсуждения в #63. 

Что имеем - Три баланса аренды, два счета предприятия.

Отделяем мух от котлет - Расчет трех балансов аренды не связан с расчетом счетов предприятия в том смысле, что эти задачи можно решать по отдельности в любом порядке или параллельно.

Каждый из трех балансов аренды (Арендный,Ремонтный,Штрафной) рассчитываются одинаково исходя из наличия диапазона дат (создание аренды - момент расчета баланса), а также списаний и платежей в этом диапазоне на аренде (отсюда следует, что списания и платежи должны быть связаны с конкретной датой и конкретной арендой):

![img1](https://cloud.githubusercontent.com/assets/4660424/8047097/ca355198-0e49-11e5-8416-972941013132.jpg)

История статусов аренды влияет на наличие регулярного списания в первом из трех балансов (Арендный), для примера на рисунке фиолетовая черта (Приостановлено) совпадает с отсутствием очередного списания.

4.(четвертое) Из двух счетов предприятия главный для нас счет1 - "В Кассе". Это те деньги которые копятся в сейфе до выемки. В момент выемки необходим контроль соответствия фактической суммы сумме "по чекам", отсюда важность счета.

Расчет происходит на основе диапазона дат (дата предыдущей выемки - дата текущей выемки), платежей связанных с этим диапазоном, а также возвратов денег из кассы (сейчас есть понимание что это возврат залога для аренд в статусе "Под расчет").

![img2](https://cloud.githubusercontent.com/assets/4660424/8047447/2567e37e-0e4e-11e5-9ade-0a7eb82a49a4.jpg)

UPD п. 4 (Счет "В кассе") : в формуле забыл Авансы которые вносят новые водители, их же тоже вносят в кассу:
![formula](https://cloud.githubusercontent.com/assets/4660424/8055155/352d29f6-0ea6-11e5-9829-da9eaf4dc80a.jpg)

"А штрафы и аренды покрываются уже из кармана?" - Тема мух и котлет здесь актуальна даже больше. Расчеты балансов аренд и счета кассы это задачи "получения" денег владельцем бизнеса. Учет реальных расходов которые он оплачивает, таких как реальный ремонт машины, ЗП сотрудников, оплата штрафов и т.д. происходит со счета "В кармане" после выемки из кассы и является не связанной задачей настолько, что можно вынести ее во второй релиз. Суммы этих трат хранятся в отдельной таблице, их агрегация для отчетов является отдельной задачей не связанной с расчетом балансов и счетов. Для наглядности картинка процессов и их изолированности друг от друга (п.2 нас вообще не касается, мы обеспечиваем только мотивацию наличием трех балансов):
![default](https://cloud.githubusercontent.com/assets/4660424/8055568/2545b8ac-0ea9-11e5-8075-1eff8d3b8689.jpg)

**Comment by sedovalx** [comment]
@hodkoff2 @Argelein 
Я сделал так, что у нас теперь нет отдельных сущностей платежа, штрафов и ремонта. У нас теперь есть понятие операции над счетом. Операция - это некоторое кол-во денег, зачисленное на некоторый счет. Операция всегда связана с какой-либо арендой. Счета сейчас, как сказано выше, - аренды, ремонтный и штрафной. Т.е. у операции есть свойство "accountType" с типом счета (перечисление). Сделано только на сервере. На клиенте, надеюсь, Кирилл поменяет:
- удалить списки, редактора, маршруты, мастера для ремонта и штрафов
- список, редактор, мастер, марштуры платежа переделать на операцию

Дальнейший шаг - соответствующие изменения в кассовой форме, чтобы правильно считались балансы. Это за мной. Я пока ничего не коммитил, т.к. еще не доделал серверную часть полностью - падают тесты. Завтра-послезавтра, надеюсь, будет. 

Кирилл, пока можешь переделать платеж на операцию на клиенте. Список полей у операции такой же как у платежа + 
- поле accountType перичислимого типа: "Rent", "Fine", "Fepair". 
- поле rentDisplayName: String, где будет полное имя аренды.

Не пытайся в списке операций отображать полное имя аренды, вычисляя его по имени машины и водителя, как ты делал раньше. Это работает медленно. Если есть вопросы, задавай.

**Comment by kirzas** [comment]
@sedovalx 
создал операции, но платежи не были прикручены ни к чему, операции я тоже не прикручивал.
ответил на твой todo

**Comment by kirzas** [comment]
А можно несколько человек на задачу делать?

**Comment by sedovalx** [comment]
@Argelein что за todo? Не помню. Несколько человек тут нельзя, кажется. 
Да, операции ни к чему не прикручены сейчас. План такой: в форме кассира создать кнопки:
- Добавить платеж
- Добавить штраф
- Добавить ремонт
  По нажатию на них должен открываться мастер операции с заранее выбранным типом счета.

**Comment by kirzas** [comment]
@sedovalx 
ок, я сейчас сделаю

**Comment by kirzas** [comment]
@sedovalx 
1. сделал, посмотри, плиз.
2. там билды сломались, мне письмо от трависа пришло, но ошибки я не понял, надеюсь, что сейчас уйдут.
3. сохранение операций не работает, т.к. адаптер fixtures я не стал делать.
4. платежи пока не удалял, контроллер, шаблон и прочее для платежей пока все осталось

**Comment by kirzas** [comment]
@sedovalx 
С клиента тоже выпиливать?

**Comment by sedovalx** [comment]
@Argelein да

**Comment by sedovalx** [comment]
Думаю, переход выполнен. Платежи, ремонты и штрафы выпилены. Теперь только операции соответствующего типа.
