### ISSUE TITLE
Сделать форму расчета водителя

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#79]
По поводу возврата залога:

в марте с заказчиком я нафантазировал это так:

![default](https://cloud.githubusercontent.com/assets/4660424/8055708/34ddeaf4-0eaa-11e5-897b-8fd5cad1f4bf.jpg)

Теория. Идея состояла в том, что после того как водителя выгнали (или он сам ушел) должно пройти две недели (для нас это означает статус аренды "под расчет" ), за которые могут придти новые штрафы. Через две недели водитель имеет право придти за своим авансом. В этом случае проверяется кто кому что должен и водитель либо посылается нахер, либо получает свой аванс обратно (что происходит редко, чаще его шлют нахер и эта форма становится аргументом).
UI. В UI для такой аренды нужен какой-то переход, посредством кнопка скорее всего, в форму "Расчет Водителя".
В этой форме отображается калькуляция балансов его подрасчетной аренды с авансом который он вносил.

**Comment by sedovalx** [comment]
@hodkoff2 опиши тут
- что должно быть на форме расчета водителя
- какие функции она должна выполнять
- как эти функции меняют балансы
- и т.п.

**Comment by hodkovdd** [comment]
@sedovalx 
Что должно быть на форме:

   Поля с информацией по закрываемой аренде водителя :
- ФИО водителя
- баланс Арендный
- баланс Ремонтный
- баланс Штрафной
- Залог (он же Аванс) которой он вносил в момент создания.
- Сумма всех значений выше
  
  Кнопки:
- Расчитать. Действие: Сумма всех значений вычитается из счета "в Кассе". перевод аренды в статус "Закрыта". 
- Отмена. Действие: ничего.

**Comment by hodkovdd** [comment]
@sedovalx 
готовность? Серверная, клиентская стороны?

**Comment by sedovalx** [comment]
@hodkoff2 
Как должно вычисляться поле Аренда? Это поле соответствует колонке "Текущий баланс арендный" из кассовой формы?
Закрытие аренды делается только через расчет или же можно через редактор аренды тоже?

В целом, ничего по этому пока нет. Понятия "счет в Кассе" тоже пока в модели нет. Я не уверен, что я его правильно понимаю. Подзабыл уже. Нужны пояснения и примеры.

**Comment by hodkovdd** [comment]
@sedovalx 
Как должно вычисляться поле? - поля Аренда, Штраф, Ремонт здесь это те же значения их кассовой формы "Текущий Баланс ХХХ". Залог - то что указывалось в поле залог при создании аренды.
"счет в Кассе" - Ок, напишу\нарисую, выложу, тогда обсудим.

**Comment by sedovalx** [comment]
Мне кажется, на форме расчета не помешает видеть историю операций и смен статусов по аренде. Скажем, сверху сводка:
- Аренда
- Ремонт
- Штрафы
- Залог
- Кол-во активных минут аренды
- Итого

А снизу таймлайн с операциями и переходами статусов. Сразу бы сняло много вопросов. В принципе, это вполне реализуемо.

**Comment by hodkovdd** [comment]
@sedovalx 
Звучит круто, однако не уверен, что правильно понимаю что такое "сводка". Это закладки, а в каждой более подробная инфа в виде таблиц? И как выглядит таймлайн? Нужен рисованный макет для утверждения, если объяснишь подробнее я смогу нарисовать.

**Comment by hodkovdd** [comment]
таймлайн по аренде: https://github.com/sedovalx/taxi/issues/85#issuecomment-119327603
@sedovalx ответишь про "сводки"?

**Comment by sedovalx** [comment]
см #85 
Под сводкой понимается просто набор полей с итоговой информацией. Набор перечислен выше. А под ним таблица/список/таймлайн с хронологией всех событий по аренде.

**Comment by sedovalx** [comment]
Смотри https://github.com/sedovalx/taxi/issues/85#issuecomment-120632929
