### ISSUE TITLE
Создание аренды без статуса

### ISSUE THREAD

**Issue by hodkovdd** [sedovalx/taxi#82]
Сейчас есть возможность создать аренду без указания ее статуса:
![8](https://cloud.githubusercontent.com/assets/4660424/8501898/96797592-21b2-11e5-8a24-113a32623e37.png)
При этом ничего не происходит. Инстинктивно нажимаешь еще пару раз Создать.
Оказывается каждый раз аренда создается с пустым статусом:
![9](https://cloud.githubusercontent.com/assets/4660424/8501998/cb482d30-21b3-11e5-9196-071498e7db7e.png)
Если после этого все таки поставить статус и создать правильную аренду, она создастся:
![10](https://cloud.githubusercontent.com/assets/4660424/8502015/e9cb7690-21b3-11e5-9ad2-bcfa34410c0e.png)
но в Кассовой форме отображаться не будет пока не удалишь "неправильные " аренды.

**Comment by hodkovdd** [comment]
@sedovalx @Argelein

**Comment by sedovalx** [comment]
Поправлено
