### ISSUE TITLE
Фильтрация в кассовой форме

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#83]
Нужна фильтрация по номеру автомобиля и ФИО водителя. Вероятно, нужно ориентироваться не на точное совпадение ФИО и номера, а на вхождение.

Сервер будет ожидать от клиента следующие возможные параметры фильтрации:
- car
- driver
- data (в формате 2012-12-24T16:45:00.000+05:30)
  Все параметры опциональные. Если дата не передана, то будет использована текущая по серверному времени. Если передана, то список будет построен на указанную дату. Т.о. если указана прошлая дата, то будут не учтены какие-то операции, которые произошли уже после указанной даты. Если же передана еще не наступившая дата, то будут учтены все операции, а так же несколько **будущих** списаний с арендного баланса. Это дает возможность узнать, какой баланс будет у аренды через несколько дней.

Пример запроса: `http://localhost:9000/cashier-list?car=А345ВВ12&driver=Засла`

На клиенте нужно добавить блок фильтра по номеру машины и ФИО над кассовой формой, по аналогии со списком пользователей.

**Comment by sedovalx** [comment]
@Argelein дальше дело за тобой

**Comment by sedovalx** [comment]
Побочным эффектом получилось, что можно искать не просто по номеру машины, а по вхождению в значения столбца "Машина", кассовой формы. Т.е. можно поискать все Mitsubishi, например.

Так что, может быть, имеет смысл назвать фильтр не "Номер машины", а просто "Машина".

**Comment by kirzas** [comment]
@sedovalx 
@hodkoff2 
сделал фильтрацию по машине и по водителю.
Есть проблемы:
1. перезагружается страница полностью, в отлтчте от того, как работает с пользователями. Полагаю связано с тем, что каждый раз идет запрос на сервер.
Могу предложить сделать еще одно булиновское свойство в контроллере, которое показывает, отрыт ли фильтр или закрыт. Это не решит перезагрузки страницы, но она хотя бы быудет перезагружена в том же виде.
2. Фильтр case-sensitive. мне кажется неудобно.

**Comment by sedovalx** [comment]
С 2 согласен. С перезагрузкой страницы надо смотреть, такого быть не должно.

**Comment by hodkovdd** [comment]
@sedovalx
Фильтр case-sensitive - можно сделать нечувствительным?

**Comment by sedovalx** [comment]
Сделаю сегодня, если успею.

**Comment by sedovalx** [comment]
С перезагрузкой страницы не понял. На самом деле это не перезагрузка всей страницы, а перерисовка шаблона cashier-list.hbs. Почему тут так происходит, а для пользователей просто данные обновляются, непонятно. @Argelein сделай пока тот флаг, о котором говорил. Ну и, если время есть, поизучай, что в чем разница. Так же можно почитать и подумать, как перезагружать данные, не вызывая transitionToRoute. Возможно в документации по Ember что-то такое есть.

Но вообще странно.

**Comment by sedovalx** [comment]
@Argelein вот вариант по-перспективнее http://guides.emberjs.com/v1.10.0/routing/specifying-a-routes-model/#toc_refreshing-your-model

**Comment by sedovalx** [comment]
Пока и так сойдет.
