### ISSUE TITLE
Реализация учета списаний с арендного баланса

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#84]
Сейчас в кассовой форме при отображении столбца "Текущий баланс арендный" учитываются только зачисления на баланс. Однако нужно учитывать и списания. 

На самом деле хранить факты списаний в БД мы не будем. Будем вычислять, исходя из времени активного состояния аренды и указанного для машины тарифа:
- будем считать с точностью до минуты
- предполагая, что тариф для машины указан в рублях в день, вычисляем тариф за минуту
- по истории статусов аренды вычисляем кол-во минут активного состояния аренды с момента ее создания до некоторого момента Х, который мы указываем в качестве параметра
- по умолчанию момент Х - текущее серверное время
- полученное кол-во минут умножаем на тариф в минуту и получаем сумму списаний
- сумму списаний вычитаем из текущего арендного баланса

**Comment by sedovalx** [comment]
@hodkoff2 все так?

**Comment by hodkovdd** [comment]
@sedovalx 
Саш, а откуда эти минуты взялись и пересчет в них и обратно? Какой в этом смысл? Не будет погрешностей?

**Comment by sedovalx** [comment]
Ну а как иначе рассчитать размер списаний по аренде за некоторый период? О каких погрешностях речь?
