### ISSUE TITLE
Таймлайн по аренде

### ISSUE THREAD

**Issue by sedovalx** [sedovalx/taxi#85]
Мне кажется, на форме расчета не помешает видеть историю операций и смен статусов по аренде. Скажем, сверху сводка:

Аренда
Ремонт
Штрафы
Залог
Кол-во активных минут аренды
Итого
А снизу таймлайн с операциями и переходами статусов. Сразу бы сняло много вопросов. В принципе, это вполне реализуемо.

**Comment by sedovalx** [comment]
На сервере реализован отчет, возвращающий операции и статусы по аренде. Запрос поддерживает два параметра:
- rent - обязательный идентификатор аренды
- date - дата в формате 2015-05-12T12:34:23.456+03:00, на которую строится таймлайн. Если дата не указана, то используется текущее серверное время.

Пример запроса: `http://localhost:9000/api/reports/q-rent-history?rent=257&date=2015-05-12T12:34:23.456%2B03:00`

Возвращается json в формате:

```
[
    {
        "id": 1323,
        "changeTime": "2015-05-08T19:55:29.728+03:00",
        "status": "Active",
        "operations": [
            {
                "operationTime": "2015-05-12T02:06:08.384+03:00",
                "operationId": 3022,
                "amount": 4937.07,
                "accountType": "Repair"
            },
            {
                "operationTime": "2015-05-15T17:23:11.680+03:00",
                "operationId": 3024,
                "amount": 4687.91,
                "accountType": "Rent"
            },
            {
                "operationTime": "2015-05-18T04:57:44.448+03:00",
                "operationId": 3021,
                "amount": 1228.77,
                "accountType": "Rent"
            }
        ]
    },
    {
        "id": 1324,
        "changeTime": "2015-05-29T09:28:16.704+03:00",
        "status": "Suspended",
        "operations": [
            {
                "operationTime": "2015-05-12T02:06:08.384+03:00",
                "operationId": 3022,
                "amount": 4937.07,
                "accountType": "Repair"
            },
            {
                "operationTime": "2015-05-15T17:23:11.680+03:00",
                "operationId": 3024,
                "amount": 4687.91,
                "accountType": "Rent"
            },
            {
                "operationTime": "2015-05-18T04:57:44.448+03:00",
                "operationId": 3021,
                "amount": 1228.77,
                "accountType": "Rent"
            }
        ]
    }
]
```

**Comment by sedovalx** [comment]
Теперь на основе этого на клиенте можно отобразить симпатичную историю статусов аренды и операций по ним. Наверное сам сделаю.

**Comment by sedovalx** [comment]
![](http://i.imgur.com/aHgemDO.jpg)

Набросок.

**Comment by sedovalx** [comment]
Выровнено конечно все должно быть. Смысл в том, что в хронологической последовательности упорядочены
- Статусы аренд
- Списания
- Платежи

Сразу видна вся история смены статусов, и какие операции были в течение статуса. Это может быть не таблица. В принципе это и таблицей сделать можно, но тогда смены статусов теряются на общем фоне, а мне кажется удобнее было бы, если бы они выступали в качестве групп для операций. Можно подумать, вероятно этого же и в табличной форме можно достичь.

**Comment by hodkovdd** [comment]
@sedovalx 
Саша, что с тамлайном? Я его жду или Сводную таблицу по Аренде? Они выполняют одну и ту же задачу, нужно понять можно ли таймлайном вообще заменить Сводную.

**Comment by sedovalx** [comment]
@hodkoff2 сегодня займусь этим. В списке аренд при нажатии на "Редактировать" будет открываться редактор аренды. У него будет две закладки:
- Сводка. Тут будут текущие балансы по платежам, штрафам и ремонтам. Будет указана машина, водитель, депозит, дата начала аренды и комбик со статусом.
- История. Тут будет выведена вся история статусов и операций по аренде. 

Эта же форма будет выполнять роль формы расчета водителя. Тут вся необходимая информация для этого есть, по-моему. 

Так же можно в кассовую форму добавить кнопку, которая будет открывать этот редактор для выбранной аренды.
