### ISSUE TITLE
Создание Штраф\Ремонт записей

### ISSUE THREAD

**Issue by hodkovdd** [sedovalx/taxi#86]
from @sedovalx 
to @hodkoff2
Кстати, по поводу самих Штраф/Ремонт записей. А не это не то же самое внешне, как если б мы создавали отрицательный платеж за штраф или ремонт? Если так, то это можно довольно просто реализовать на клиенте. Или вообще оставить как есть. По первому времени не обломятся, думаю, будут минус указывать в операции.

**Comment by sedovalx** [comment]
Это что такое?

**Comment by hodkovdd** [comment]
@sedovalx 
то что ты предлагаешь, это костыль. Однако может сработать. У формы создания Штраф\Ремонт записей есть обязательное поле Описание нарушения\повреждения, а также в будущем появиться связанное поле фотография. В форме Платежа есть поле Явка, которое не к месту в штрафах\списаниях:
![16](https://cloud.githubusercontent.com/assets/4660424/8512474/cfced152-234c-11e5-8490-7858e7e0b8c2.png)

**Comment by hodkovdd** [comment]
1. нужно понять нужно ли городить костыль или сразу сделать разные формы. Так ли это сложно?

**Comment by sedovalx** [comment]
Все это ерунда, если б не обязательность поля с описанием. В операции тоже есть поле с комментарием, но оно не обязательно. А так почти один в один, что платежи, что сами ремонты  и штрафы. Только знак числа отличается. Галку с явкой можно легко скрыть.
Но ты прав, лучше сделать раздельные сущности. Операции разделить на платежи и списания. В принципе, это не очень сложно. Один свободный вечер для доделки сервера и пара вечеров для клиента.
Поле явки нужно только для платежа за аренду? Платежи за штраф и ремонты без явки происходят?

**Comment by sedovalx** [comment]
@hodkoff2 а все же, давай пофантазируем. Ниже перечислю сходства списаний и платежей:
- привязаны к аренде
- имеют дату операции
- имеют дату создания
- имеют некоторую сумму (отрицательную или положительную)
- могут иметь несколько приложенных файлов
- имеют необязательный комментарий
- имеют обязательное описание, которое **в случае платежей** может автоматически заполняться на клиенте по некоторому шаблону, а в случае списаний его нужно будет самостоятельно заполнить 
- имеют поле явки, которое в случаях, где явка не подразумевается, и галочка не нужна, заполняется автоматически значением по умолчанию - false

Ничего не упустил? С этой точки зрения и платежи, и списания - это суть операции просто с разным знаком суммы и разными обязательными описаниями.

**Comment by sedovalx** [comment]
Чтобы не определять тип операции по знаку можно добавить битовый признак являетсяПлатежом, но со знаком как-то элегантнее и логичнее. Если отрицательная сумма - очевидно это списание, а если положительная, то платеж. В UI можно сделать отдельные кнопки на "Добавить штраф" и "Добавить платеж за штраф". Они будут открывать почти одинаковую форму, только у штрафа будет предзаполнено/скрыто поле с описанием. А при сохранении операции для штрафа будет проставляться знак минус.

**Comment by hodkovdd** [comment]
@sedovalx 
Ты предлагаешь расширить количество свойств сущности настолько, чтобы в нее помещались и платежи и списания. Я примерно так себе и представил твою идею. С точки зрения наполнения ок, мы их занесли и балансы считаются верно просто по сумме чисел. А когда придется извлекать, например для сводной таблицы по конкретной аренде, получится красиво их распарсить на платежи, списания, ремонты, штрафы? В целом вопрос такой - будут ли ограничения по манипуляциям этими записями после их занесения в базу если мы свалим  их в одну кучу? Насколько высоки будут накладные расходы на проверки что это за запись при извлечении (не станет ли подтормаживать та же сводная таблица по аренде спустя полгода год, когда накопятся данные) ? 

Ничего не упустил?
- Тип операции (аренда, штраф, ремонт)

Поле явки нужно только для платежа за аренду? 
Заполненное поле явка означает, что водитель приехал и показал машину. Сделать он это может и не оплатив аренду. Таким образом поле явка нужно для всех видов платежей.

**Comment by sedovalx** [comment]
У каждой операции есть тип: аренда, штраф, ремонт. Добавляем сюда знак операции и получаем:
- Платеж за аренду
- Платеж за штраф
- Платеж за ремонт
- Ремонт
- Штраф

Что за сводная таблица по аренде?

**Comment by hodkovdd** [comment]
@sedovalx 
![17](https://cloud.githubusercontent.com/assets/4660424/8596696/83aa977e-2659-11e5-9d6f-f0374acf75c4.png)
обсуждалось здесь: https://github.com/sedovalx/taxi/issues/76

**Comment by hodkovdd** [comment]
@sedovalx 
Чтобы не громоздить кучу ненужных кнопок в интерфейсе КС как это сделано сейчас:
![18](https://cloud.githubusercontent.com/assets/4660424/8597097/0e9cc224-265c-11e5-965c-9fdb292c4f43.png)
 можно ли сделать создание операции через унифицированную форму как на дизайн-схеме был задуман платеж:
![19](https://cloud.githubusercontent.com/assets/4660424/8597144/51837a4c-265c-11e5-9ce2-54ebc101dfac.jpg)
только с поправкой на то что мы обсудили выше:
![20](https://cloud.githubusercontent.com/assets/4660424/8597544/b7c5e1bc-265e-11e5-817b-ee4f77c9f01f.jpg)

:

**Comment by sedovalx** [comment]
Да в общем-то можно. Только не лучше ли сделать две кнопки: 
- Создать платеж
- Создать списание
  и избавиться от первой формы? @Argelein ты как считаешь?

**Comment by kirzas** [comment]
@hodkoff2 @sedovalx 
да, давайте так сделаем. ощущение хождения по кругу имеется :)
тогда это будет как и раньше открытие формы с выбором типа платежа. А от того, выбрано списание или платеж, будет зависеть знак перед суммой, верно?
т.е. в интерфейсе и при создании платежа и при создании списаний удет положительная сумма, но на сервер будет уходить со знаком + или -, в зависимости от того, по какой кнопке перешли из кассовой формы.
Я правильно понял?

**Comment by hodkovdd** [comment]
@Argelein @sedovalx 
"...т.е. в интерфейсе и при создании платежа и при создании списаний удет положительная сумма, но на сервер будет уходить со знаком + или -, в зависимости от того, по какой кнопке перешли из кассовой формы..." - по мне да, Саша, согласен?

В случае Списаний обязательные поля Описание, Фото можно называть одинаково, просто Описание и Фото. Тогда все складывается.

**Comment by sedovalx** [comment]
@hodkoff2 @Argelein 
Да, вроде бы все так. В кассовой форме нужно сделать две кнопки:
- Создать платеж
- Создать списание

По нажатию должен открываться редактор операции с полями:
- Тип операции (платеж или списание). Нередактируемое.
- Аренда. Нередактируемое.
- Дата операции. Текущее время. Нередактируемое.
- Тип баланса. Для списания - это штрафы и ремонты. Для платежей - это аренда, штрафы и ремонты.
- Сумма
- Описание
- файлы... (пока не делаем)

В поле суммы пользователь всегда будет вводить положительное число. При сохранении нужно смотреть, платеж это или списание, и подставлять нужный знак в сумму перед отправкой результата на сервер.

Путь: $/cashier-list/rents/12/operations/new?type=plus (или minus)

**Comment by sedovalx** [comment]
Входит в план-минимум #95

**Comment by kirzas** [comment]
@hodkoff2 @sedovalx 
Проверьте, пожалуйста, все ли как вы планировали. Я пока закрываю. Если что переоткройте.

**Comment by hodkovdd** [comment]
@Argelein 
поля "явка" в форме "Charge" (новое списание) не должно быть. Значение False должно быть зашито.
Поле "явка" в форме "Payment" (новый платеж) сейчас не меняет значение в колонке Явка в КС. Почему?

**Comment by kirzas** [comment]
@hodkoff2 
а может быть платеж без явки?
может строго пришить явку к типу операции?
платеж - явка true, списание - явка false?

**Comment by hodkovdd** [comment]
@Argelein 
платеж можно передать через другого водителя, оставить в почтовом ящике в конверте и прочее. Другими словами платеж может быть с явкой и без нее.
У списания явки вообще не должно быть, это просто последствие того что мы платежи и списание храним в одной сущности "операция".

**Comment by kirzas** [comment]
@hodkoff2 @sedovalx 
сейчас в модели явка по умолчанию true
предлагаю такой вариант:
1. явка по умолчанию false;
2. в платеже ее можно поставить руками;
3. в списании она readonly

устраивает?

**Comment by sedovalx** [comment]
@Argelein 
в UI списания поле явки должно быть скрыто. Какое значение явки по умолчанию должно быть при создании платежа, путь скажет @hodkoff2.

**Comment by hodkovdd** [comment]
@Argelein 
значение явки по умолчанию должно быть при создании платежа - false - пусть ручками ставит, подтверждая, что явка была.

**Comment by kirzas** [comment]
@hodkoff2 @sedovalx 
На клиенте сделал, осталось это:

Поле "явка" в форме "Payment" (новый платеж) сейчас не меняет значение в колонке Явка в КС.
Это на сервере надо сделать ведь?

**Comment by sedovalx** [comment]
@Argelein убедись, что на сервер уходит верное значение явки. Так-то без всяких изменений работать должно. Кстати, в КС в столбце явки галка отображается только в том случае, если операция была произведена в день просмотра формы.

**Comment by kirzas** [comment]
@sedovalx 
нормально уходит "presence: true":
operation: {changeTime: "2015-07-21T20:55:55.622Z", amount: 44, accountType: "Rent", rentDisplayName: null,…}
accountType: "Rent"
amount: 44
changeTime: "2015-07-21T20:55:55.622Z"
comment: null
creationDate: null
creator: null
editDate: null
editor: null
operationType: "payment"
<b>presence: true</b>
rent: "94"
rentDisplayName: null
Еще один момент придумал, но заведу на это дела две других задачи.
