### ISSUE TITLE
Поле ИТОГО в Кассовой Форме: Формула значения

### ISSUE THREAD

**Issue by hodkovdd** [sedovalx/taxi#90]
@sedovalx 

Сейчас считает непойми что, вроде как отрицательную сумму всех балансов по модулю, а может и нет, но точно не то, что надо.
Должно быть:
ИТОГО = сумма отрицательных значений (Аренда,Ремонт,Штраф)
Пример:
![23](https://cloud.githubusercontent.com/assets/4660424/8635540/e288ade4-282f-11e5-8b90-45ac333aafec.png)
- У Васи все хорошо по Арендному Балансу,но есть долги за Штрафы и Ремонт. Его ИТОГО = (-500)+(-2500)=-3000. Положительная Аренда не добавляется.
- У Пети  плохо с Арендой и Ремонтом, зато нет Штрафов. Его ИТОГО = (-2000)+(-1500)=-3500 

смысл поля ИТОГО в том чтобы помочь Кассиру решить его задачу - получить денег с Водителя столько чтобы Водитель не был должен ни по одному из Балансов, при этом Кассир не может перекидывать деньги с Баланса на другой Баланс(то есть положительная сумма на одном Б не спасает водителя от отрицательных значений в других Б).

**Comment by sedovalx** [comment]
Входит в план-минимум #95
