### ISSUE TITLE
Сводная таблица по выбранной в КС Аренде

### ISSUE THREAD

**Issue by hodkovdd** [sedovalx/taxi#94]
@sedovalx @Argelein 
![detalization spisation](https://cloud.githubusercontent.com/assets/4660424/8635762/1a7d3e18-283f-11e5-99f6-93541becf534.png)

Это место просмотра операций по Аренде, операции в нем идут в хронологическом порядке по умолчанию. Здесь нужно добавить фильтр и получать, при необходимости, списки только штрафов или только ремонтов или только платежей и каких именно платежей.

Отсюда навигация на форму с детализацией по выбранной операции.

**Comment by sedovalx** [comment]
А не дубль ли это? См. https://github.com/sedovalx/taxi/issues/85

**Comment by sedovalx** [comment]
Входит в план-минимум #95

**Comment by sedovalx** [comment]
Фильтра на типам операций нет, но нужен ли?

**Comment by hodkovdd** [comment]
@sedovalx 
Попробовал.
Фильтра на типам операций нет, но нужен ли? Пока нет, если нужен будет заказчик сам скажет, тут впереди паровоза не стоит.
Замечания:
- время платежей всегда 0:00
  ![30](https://cloud.githubusercontent.com/assets/4660424/8640329/27ec0322-28fd-11e5-986c-f8b76e7adea8.png)

---
- При переходе на детализацию операции нет поля "Внес" с указанием пользователя, создавшего операцию:

![31](https://cloud.githubusercontent.com/assets/4660424/8640346/d0b46d14-28fd-11e5-8bd0-a314f6be473a.png)

**Comment by sedovalx** [comment]
С клиента неверное время приходит. Все время полночь. @Argelein нужно поправить поле ввода даты для операции.

**Comment by hodkovdd** [comment]
@sedovalx @Argelein 
Сейчас вообще нет данных об операциях (ни платежей ни списаний):
![37](https://cloud.githubusercontent.com/assets/4660424/8701587/6fcb430e-2b1b-11e5-82f5-4198dd074801.png)

**Comment by sedovalx** [comment]
@hodkoff2 
Пока не заводи новых данных на стенде, я посмотрю запросы.

**Comment by sedovalx** [comment]
@hodkoff2 проблема в том, что при создании операции на сервер отправляется неверное время ее создания. Это из-за того компонента, что мы используем для выбора времени. Точнее для выбора даты, т.к. он сейчас позволяет выбирать именно дату, а не время. В результате имеем сбои в расчете истории операций. @Argelein уже отметил эту проблему.

**Comment by hodkovdd** [comment]
@sedovalx @Argelein 
Кто и когда ее решит?

**Comment by sedovalx** [comment]
@hodkoff2 она уже должна быть решена https://github.com/sedovalx/taxi/issues/100

**Comment by kirzas** [comment]
@sedovalx 
Здесь остается последнее замечание от Димы https://github.com/sedovalx/taxi/issues/94#issuecomment-120768838, пункт 2:
    При переходе на детализацию операции нет поля "Внес" с указанием пользователя, создавшего операцию

Я попробовал добавить creator, но там пусто. Полагаю ,что сервер при запросе q-rent-history не отдает этого свойства.

**Comment by sedovalx** [comment]
Все верно, сервер не отдает сейчас. Но поле на сервере заполняется. Так что нужно только немного поправить q-rent-history на сервере. Но самостоятельно вы вряд ли это сделаете.

**Comment by hodkovdd** [comment]
@sedovalx @Argelein 
1. ... уже должна быть решена https://github.com/sedovalx/taxi/issues/100...  Не решена, операций нет, переоткрыл.

**Comment by sedovalx** [comment]
@Argelein у тебя тоже истории операций не видно?

**Comment by kirzas** [comment]
у меня видно, сейчас еще раз проверил, скрин внизу
![capture](https://cloud.githubusercontent.com/assets/10670155/8835004/8ef586e0-30c0-11e5-9e69-3b1a9537aa43.PNG)

**Comment by kirzas** [comment]
@hodkoff2 
Дим, проверь, что ты создал для аренды, которую смотришь списания и платежи.

**Comment by hodkovdd** [comment]
@Argelein @sedovalx 
Проверил сейчас, операции отображаются, Остался вопрос о том что же было, в себе уверен, перед тем как переоткрыть все 3 раза проверил, скриншоты доказывают, что аренда та. Если это баг то еще всплывет. 
Теперь не понятно зачем здесь кнопка Сохранить -  сводка доступна только для чтения, тут нечего сохранять.

**Comment by kirzas** [comment]
после решения #97 тут все будет немного по-другому, сохранить либо не будет, либо будет зачем :)
тут забей на нее.

**Comment by kirzas** [comment]
Итак :) остается только один момент:

---

Здесь остается последнее замечание от Димы #94 (comment), пункт 2:
При переходе на детализацию операции нет поля "Внес" с указанием пользователя, создавшего операцию

---

Я попробовал добавить creator, но там пусто. Полагаю ,что сервер при запросе q-rent-history не отдает этого свойства.

---

Все верно, сервер не отдает сейчас. Но поле на сервере заполняется. Так что нужно только немного поправить q-rent-history на сервере. Но самостоятельно вы вряд ли это сделаете.

**Comment by hodkovdd** [comment]
Ждем Сашу тут?

**Comment by kirzas** [comment]
ага
или можешь попробовать сам :)

**Comment by sedovalx** [comment]
Сегодня-завтра займусь этим.

**Comment by hodkovdd** [comment]
@sedovalx 
а что значит null null в поле "внес"? это псевдоним admin?

**Comment by sedovalx** [comment]
Это значит, то имя и фамилия для админа не заполнены.

**Comment by hodkovdd** [comment]
@sedovalx 
Там же сейчас есть кнопка Сохранить
Я поменял все даты операций, часть пропала потому что я перенес их в будущее, часть переехала в прошлое. Непорядок
В сводке не должно быть возможности менять что либо.
К тому же можно менять сумму!)))

**Comment by sedovalx** [comment]
Тогда вовсе не останется возможности что-то подправить в операциях. А такая необходимость всегда возникает.

**Comment by hodkovdd** [comment]
Как ты себе это представляешь?

**Comment by sedovalx** [comment]
В смысле зачем подправлять? Ошиблись в записи суммы/не тот тип операции указали/явку забыли проставить и сохранили. Дату наверное не имеет смысла давать редактировать, хотя хз.

**Comment by hodkovdd** [comment]
Какое это будет доказательство наличие\отсутствия платежей и их количества, если их можно менять в любой момент? Если кто то ошибается в момент ввода, отмена операции быть должна, безусловно, через админа.
Пример:
1.В момент платежа водитель передает деньги кассиру.
2.Кассир вносит данные, сохраняет их. Водитель убеждается что его платеж зафиксирован верно, спокойно уходит.
...
n. Возникает конфликт (Водитель: Как не платил на прошлой неделе, еще как платил!)
n+1. Кассир показывает сводку по аренде где нет платежа.
n+2. Водитель парирует - Вы же б_я здесь все меняете постоянно на__й. не_*т!
Тупик...

**Comment by sedovalx** [comment]
Ну ведь так же и через админа можно поменять, а результат -> n+1 -> n+2. Разве нет? Если водитель хоть раз заметит, что что-то в записях поменялось (пусть даже ошибка исправилась), то результат тот же.

**Comment by sedovalx** [comment]
Можно конечно режим просмотра операции сделать по умолчанию, а если ты админ, то тебе в режиме редактирования открывается.

**Comment by hodkovdd** [comment]
Да, смысл обращения к Админу как к арбитру между Кассиром и Водителем, в идеале по обоюдному согласию. Типа ввели неверные данные Кассир сам решает брать на себя ответственность за возможный конфликт или сразу донести инфу до водителя и по договоренности с ним эскалировать проблему до Админа. Отменить операцию такую то потому то. А то рискуем бесконтрольные изменения получить. Нужна точка отвественности за изменения и Кассир на эту роль ну никак не годится, по причине широких возможностей для серых схем.
Если конфликт все равно возникнет то Админ как ответственный принимает оргмеры.

**Comment by sedovalx** [comment]
Хорошо, тогда для всех кроме админа сделаем только просмотр. Эта задача относится к #96 больше, но точно не сюда. Завел новую #111
