### ISSUE TITLE
БАГ: Дубли в КС

### ISSUE THREAD

**Issue by hodkovdd** [sedovalx/taxi#99]
@sedovalx 
Если создавать платеж по Аренде более одного раза, при этом сначала указывать явку, а затем без указания явки (можно наоборот, эффект тот же)
![35](https://cloud.githubusercontent.com/assets/4660424/8640406/9034ab76-28ff-11e5-95c7-4856db7186ad.png)
Появляется дубль Аренды в КС, при повторении действий дубли продолжают копиться:
![32](https://cloud.githubusercontent.com/assets/4660424/8640410/a61c56fa-28ff-11e5-8b27-d43e3cbd37d4.png)

:

**Comment by sedovalx** [comment]
Вместо того, чтобы писать "БАГ" в названии нужно указывать метку bug для задачи. Это делается справа от текста задачи.
![image](https://cloud.githubusercontent.com/assets/9218022/8640433/06f07bcc-2901-11e5-8c1f-c36ebe2bca30.png)

**Comment by hodkovdd** [comment]
@sedovalx 
Спасибо, буду ставить Label'ы :)
